// const ClothesData=[

//     {
//         id:'00021',
//       name:'Logo T-shirt',
//       size:'S',
//       color:'Black',
//       price:550,
//       image:require('../Shop/shopImage/LoTshirt-black.png'),
//     },
//     {
//         id:'00022',
//       name:'Logo T-shirt',
//       size:'S',
//       color:'White',
//       price:550,
//       image:require('../Shop/shopImage/LoTshirt-white.png'),
//     },
//     {
//         id:'00023',
//         name:'Logo T-shirt',
//         size:'S',
//         color:'Red',
//         price:550,
//         image:require('../Shop/shopImage/LoTshirt-red.png'),
//     },
//     {
//         id:'00024',
//       name:'Logo T-shirt',
//       size:'M',
//       color:'Black',
//       price:550,
//       image:require('../Shop/shopImage/LoTshirt-black.png'),
//     },
//     {
//         id:'00025',
//       name:'Logo T-shirt',
//       size:'M',
//       color:'White',
//       price:550,
//       image:require('../Shop/shopImage/LoTshirt-white.png'),
//     },
//     {
//         id:'00026',
//         name:'Logo T-shirt',
//         size:'M',
//         color:'White',
//         price:550,
//         image:require('../Shop/shopImage/LoTshirt-red.png'),
//     },
//     {
//         id:'00027',
//       name:'Logo T-shirt',
//       size:'L',
//       color:'Black',
//       price:550,
//       image:require('../Shop/shopImage/LoTshirt-black.png'),
//     },
//     {
//         id:'00028',
//       name:'Logo T-shirt',
//       size:'L',
//       color:'White',
//       price:550,
//       image:require('../Shop/shopImage/LoTshirt-white.png'),
//     },
//     {
//         id:'00029',
//         name:'Logo T-shirt',
//         size:'L',
//         color:'White',
//         price:550,
//         image:require('../Shop/shopImage/LoTshirt-red.png'),
//     },
//     {
//         id:'00030',
//       name:'Logo Hoodie',
//       size:'S',
//       color:'Black',
//       price:1050,
//       image:require('../Shop/shopImage/LoHoodie-black.png'), 
//     },
//     {
//         id:'00031',
//       name:'Logo Hoodie',
//       size:'M',
//       color:'Black',
//       price:1050,
//       image:require('../Shop/shopImage/LoHoodie-black.png'), 
//     },
//     {
//         id:'00032',
//       name:'Logo Hoodie',
//       size:'L',
//       color:'Black',
//       price:1050,
//       image:require('../Shop/shopImage/LoHoodie-black.png'), 
//     },
//     {
//         id:'00033',
//       name:'Logo Hoodie',
//       size:'S',
//       color:'Red',
//       price:1050,
//       image:require('../Shop/shopImage/LoHoodie-red.png'), 
//     },
//     {
//         id:'00034',
//       name:'Logo Hoodie',
//       size:'M',
//       color:'Red',
//       price:1050,
//       image:require('../Shop/shopImage/LoHoodie-red.png'), 
//     },
//     {
//         id:'00035',
//       name:'Logo Hoodie',
//       size:'L',
//       color:'Red',
//       price:1050,
//       image:require('../Shop/shopImage/LoHoodie-red.png'), 
//     },
//     {
//         id:'00036',
//       name:'Logo Hoodie',
//       size:'S',
//       color:'white',
//       price:1050,
//       image:require('../Shop/shopImage/LoHoodie-white.png'), 
//     },
//     {
//         id:'00037',
//       name:'Logo Hoodie',
//       size:'M',
//       color:'white',
//       price:1050,
//       image:require('../Shop/shopImage/LoHoodie-white.png'), 
//     },
//     {
//         id:'00038',
//       name:'Logo Hoodie',
//       size:'L',
//       color:'white',
//       price:1050,
//       image:require('../Shop/shopImage/LoHoodie-white.png'), 
//     },
// ]
// export default ClothesData